name: Build and tests
on: [push]
jobs:
  build:
    name: Build and Test on Linux
    strategy:
      matrix:
        go-version:
          - 1.11.x
          - 1.12.x
          - 1.13.x
    runs-on: ubuntu-latest
    steps:

      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go-version }}
        id: go

      - name: Get programs
        run: |
          export GOBIN=$HOME/bin

          # build Go tools
          go get github.com/restic/rest-server
          go get github.com/restic/calens
          go get github.com/mitchellh/gox

          # minio
          wget -O $GOBIN/minio https://dl.minio.io/server/minio/release/linux-amd64/minio
          chmod 755 $GOBIN/minio

      - name: Check out code
        uses: actions/checkout@v1

      - name: Build
        run: |
          rest-server --help
          gox --help
          calens --help
          minio --help
          go run -mod=vendor build.go --goos linux
          go run -mod=vendor build.go --goos windows
          go run -mod=vendor build.go --goos darwin

      - name: Run tests
        run: |
          export PATH=$HOME/bin:$PATH
          go test -mod=vendor ./...
